apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crud-deployment
  labels:
    app: crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
      - name: crud
        image: 'gcr.io/arched-shuttle-189207/github-microservices-iosr-2017-miosr-crud:stage-0.2.7'
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: config-volume
          mountPath: /etc/appconfig/
      volumes:
      - name: config-volume
        configMap:
          name: crud-config