apiVersion: v1
kind: Service
metadata:
  name: $service-service
  labels:
    app: $service
spec:
  type: LoadBalancer
  ports:
  - port: $port
    targetPort: $esp_port
    protocol: TCP
    name: http
  selector:
    app: $service
